# Generated by Django 6.1.1 on 2026-09-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pending_email_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
